"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Upgrade = { id: string; icon: string; name: string; description: string; baseCost: number; click?: number; passive?: number };
type Angel = { id: string; icon: string; name: string; title: string; baseCost: number; damage: number };
type Milestones = Record<number, string>;
type Skill = "strike" | "burst" | "judgment";

const stages = [
  { love: 0, title: "작은 등불", mood: "아직은 조용한 시작", aura: "none" }, { love: 30, title: "따뜻한 미소", mood: "미소가 피어났어요", aura: "warm" }, { love: 100, title: "길 위의 친구", mood: "희망의 길을 걷는 중", aura: "warm" }, { love: 300, title: "마을의 위로", mood: "사람들이 모여들어요", aura: "gold" }, { love: 800, title: "평화의 노래", mood: "마음에 노래가 번져요", aura: "gold" }, { love: 2000, title: "사랑의 빛", mood: "빛이 더 깊어졌어요", aura: "light" }, { love: 5000, title: "희망의 등대", mood: "멀리까지 비추는 마음", aura: "light" }, { love: 12000, title: "기적의 손길", mood: "따뜻함이 세상을 감싸요", aura: "heaven" }, { love: 30000, title: "하늘의 평화", mood: "구름 위로 피어난 평화", aura: "heaven" }, { love: 75000, title: "영원한 사랑", mood: "사랑으로 가득 찬 완성", aura: "divine" },
];
const upgrades: Upgrade[] = [
  { id: "smile", icon: "😊", name: "따뜻한 미소", description: "클릭 애정도 +1", baseCost: 15, click: 1 }, { id: "candle", icon: "🕯️", name: "기도의 촛불", description: "초당 애정도 +1", baseCost: 70, passive: 1 }, { id: "bread", icon: "🍞", name: "나눔의 빵", description: "클릭 애정도 +6", baseCost: 280, click: 6 }, { id: "oil", icon: "🏺", name: "향유의 단지", description: "초당 애정도 +8", baseCost: 1500, passive: 8 }, { id: "halo", icon: "✨", name: "황금 후광", description: "클릭 애정도 +30", baseCost: 8000, click: 30 },
];
const angels: Angel[] = [
  { id: "baby", icon: "👼", name: "아기 천사", title: "작은 날갯짓", baseCost: 30, damage: 4 }, { id: "guardian", icon: "🪽", name: "수호 천사", title: "빛의 방패", baseCost: 150, damage: 16 }, { id: "seraph", icon: "🔥", name: "세라핌", title: "불꽃의 합창", baseCost: 620, damage: 52 }, { id: "arch", icon: "⚜", name: "대천사", title: "천상의 지휘관", baseCost: 2400, damage: 160 },
];
const dungeons = [
  { name: "바알", epithet: "지옥의 왕", icon: "♛", hp: 180, reward: 45, stage: 0, color: "#873c50" }, { name: "파이몬", epithet: "왕관의 군주", icon: "♜", hp: 600, reward: 120, stage: 1, color: "#764d8f" }, { name: "아스모데우스", epithet: "불타는 욕망", icon: "♞", hp: 1800, reward: 350, stage: 2, color: "#b04a37" }, { name: "아스타로트", epithet: "심연의 공작", icon: "☾", hp: 5100, reward: 880, stage: 3, color: "#31557c" }, { name: "바르바토스", epithet: "숲의 공작", icon: "♝", hp: 14500, reward: 2200, stage: 4, color: "#43684e" }, { name: "벨리알", epithet: "무법의 군주", icon: "♚", hp: 39000, reward: 6000, stage: 5, color: "#482e37" }, { name: "레비아탄", epithet: "바다의 뱀", icon: "☍", hp: 105000, reward: 15000, stage: 6, color: "#1d5d83" }, { name: "루시퍼", epithet: "타락한 새벽", icon: "✧", hp: 280000, reward: 42000, stage: 8, color: "#826a9d" },
];
const fmt = (value: number) => new Intl.NumberFormat("ko-KR").format(Math.floor(value));
const date = (value: string) => new Intl.DateTimeFormat("ko-KR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export default function Home() {
  const [love, setLove] = useState(0); const [levels, setLevels] = useState<Record<string, number>>({}); const [nickname, setNickname] = useState(""); const [nameDraft, setNameDraft] = useState(""); const [startedAt, setStartedAt] = useState(""); const [milestones, setMilestones] = useState<Milestones>({});
  const [grace, setGrace] = useState(0); const [angelLevels, setAngelLevels] = useState<Record<string, number>>({}); const [cleared, setCleared] = useState<number[]>([]); const [dungeonOpen, setDungeonOpen] = useState(false); const [activeDungeon, setActiveDungeon] = useState<number | null>(null); const [enemyHp, setEnemyHp] = useState(0); const [battleState, setBattleState] = useState<"fighting" | "victory">("fighting"); const [effects, setEffects] = useState<{ id: number; text: string; kind: string }[]>([]); const [cooldowns, setCooldowns] = useState<Record<Skill, boolean>>({ strike: true, burst: true, judgment: true });
  const [intro, setIntro] = useState<"welcome" | "name" | null>("welcome"); const [shopOpen, setShopOpen] = useState(false); const [profileOpen, setProfileOpen] = useState(false); const [recordOpen, setRecordOpen] = useState(false); const [popups, setPopups] = useState<{ id: number; x: number; y: number; amount: number }[]>([]); const [evolutionBurst, setEvolutionBurst] = useState(false); const [loaded, setLoaded] = useState(false); const previousStage = useRef(0);
  const clickPower = 1 + upgrades.reduce((sum, item) => sum + (item.click ?? 0) * (levels[item.id] ?? 0), 0); const passivePower = upgrades.reduce((sum, item) => sum + (item.passive ?? 0) * (levels[item.id] ?? 0), 0); const stageIndex = stages.reduce((current, item, index) => (love >= item.love * 2 ? index : current), 0); const stage = { ...stages[stageIndex], love: stages[stageIndex].love * 2 }; const nextStage = stages[stageIndex + 1] ? { ...stages[stageIndex + 1], love: stages[stageIndex + 1].love * 2 } : undefined; const progress = nextStage ? ((love - stage.love) / (nextStage.love - stage.love)) * 100 : 100;
  const jesusAttack = 12 + stageIndex * 14; const angelAttack = angels.reduce((sum, angel) => sum + angel.damage * (angelLevels[angel.id] ?? 0), 0); const activeBoss = activeDungeon === null ? null : dungeons[activeDungeon];

  useEffect(() => { const raw = window.localStorage.getItem("love-raising-save"); if (raw) try { const saved = JSON.parse(raw); setLove(saved.love ?? 0); setLevels(saved.levels ?? {}); setNickname(saved.nickname ?? ""); setStartedAt(saved.startedAt ?? ""); setMilestones(saved.milestones ?? {}); setGrace(saved.grace ?? 0); setAngelLevels(saved.angelLevels ?? {}); setCleared(saved.cleared ?? []); if (saved.nickname) setIntro(null); } catch {} setLoaded(true); }, []);
  useEffect(() => { if (loaded) window.localStorage.setItem("love-raising-save", JSON.stringify({ love, levels, nickname, startedAt, milestones, grace, angelLevels, cleared })); }, [love, levels, nickname, startedAt, milestones, grace, angelLevels, cleared, loaded]);
  useEffect(() => { if (!passivePower || !nickname) return; const timer = window.setInterval(() => setLove((value) => value + passivePower), 1000); return () => window.clearInterval(timer); }, [passivePower, nickname]);
  useEffect(() => { if (!loaded || !nickname || milestones[stageIndex]) return; setMilestones((value) => ({ ...value, [stageIndex]: new Date().toISOString() })); }, [stageIndex, loaded, nickname, milestones]);
  useEffect(() => { if (!loaded || !nickname) return; if (stageIndex > previousStage.current) { setEvolutionBurst(true); const timer = window.setTimeout(() => setEvolutionBurst(false), 1700); previousStage.current = stageIndex; return () => window.clearTimeout(timer); } previousStage.current = stageIndex; }, [stageIndex, loaded, nickname]);
  useEffect(() => { if (activeDungeon === null || battleState !== "fighting" || !angelAttack) return; const timer = window.setInterval(() => { setEnemyHp((hp) => Math.max(0, hp - angelAttack)); addEffect(`천사단 -${fmt(angelAttack)}`, "angel"); }, 1050); return () => window.clearInterval(timer); }, [activeDungeon, battleState, angelAttack]);
  useEffect(() => { if (activeDungeon === null || enemyHp > 0 || battleState === "victory") return; setBattleState("victory"); const dungeon = dungeons[activeDungeon]; setGrace((value) => value + dungeon.reward); setCleared((value) => value.includes(activeDungeon) ? value : [...value, activeDungeon]); addEffect(`승리! 은총 +${fmt(dungeon.reward)}`, "victory"); }, [enemyHp, activeDungeon, battleState]);

  const addEffect = (text: string, kind: string) => { const id = Date.now() + Math.random(); setEffects((items) => [...items, { id, text, kind }]); window.setTimeout(() => setEffects((items) => items.filter((item) => item.id !== id)), 900); };
  const price = (item: Upgrade) => Math.ceil(item.baseCost * Math.pow(1.65, levels[item.id] ?? 0)); const angelPrice = (angel: Angel) => Math.ceil(angel.baseCost * Math.pow(1.7, angelLevels[angel.id] ?? 0));
  const begin = () => { const now = new Date().toISOString(); setNickname(nameDraft.trim() || "빛의 여행자"); setStartedAt(now); setMilestones({ 0: now }); setIntro(null); };
  const clickJesus = (event: React.MouseEvent<HTMLButtonElement>) => { setLove((value) => value + clickPower); const box = event.currentTarget.getBoundingClientRect(); const id = Date.now() + Math.random(); setPopups((items) => [...items, { id, x: event.clientX - box.left, y: event.clientY - box.top, amount: clickPower }]); window.setTimeout(() => setPopups((items) => items.filter((item) => item.id !== id)), 900); };
  const buy = (item: Upgrade) => { const cost = price(item); if (love < cost) return; setLove((value) => value - cost); setLevels((value) => ({ ...value, [item.id]: (value[item.id] ?? 0) + 1 })); };
  const hire = (angel: Angel) => { const cost = angelPrice(angel); if (grace < cost) return; setGrace((value) => value - cost); setAngelLevels((value) => ({ ...value, [angel.id]: (value[angel.id] ?? 0) + 1 })); };
  const enterDungeon = (index: number) => { setDungeonOpen(false); setActiveDungeon(index); setEnemyHp(dungeons[index].hp); setBattleState("fighting"); setEffects([]); };
  const useSkill = (skill: Skill) => { if (activeDungeon === null || battleState !== "fighting" || !cooldowns[skill]) return; const detail = skill === "strike" ? { damage: jesusAttack * 3, cooldown: 1800, label: "✦ 빛의 일격" } : skill === "burst" ? { damage: jesusAttack * 8, cooldown: 6500, label: "☀ 은총 폭발" } : { damage: jesusAttack * 16, cooldown: 12000, label: "⚜ 성광 심판" }; setEnemyHp((hp) => Math.max(0, hp - detail.damage)); addEffect(`${detail.label} -${fmt(detail.damage)}`, skill); setCooldowns((value) => ({ ...value, [skill]: false })); window.setTimeout(() => setCooldowns((value) => ({ ...value, [skill]: true })), detail.cooldown); };
  const stageDots = useMemo(() => stages.map((_, index) => index <= stageIndex), [stageIndex]);
  if (!loaded) return null;
  return <>
    {intro === "welcome" && <div className="intro-overlay"><section className="intro-card"><span>✦</span><h1>예수 키우기</h1><p>작은 애정이 모여<br />빛나는 여정이 시작돼요.</p><button onClick={() => setIntro("name")}>시작하기</button></section></div>}
    {intro === "name" && <div className="intro-overlay"><section className="intro-card"><span>♥</span><h1>이름을 알려주세요</h1><p>여정의 기록에 남길<br />나만의 닉네임을 정해요.</p><input autoFocus maxLength={12} value={nameDraft} onChange={(event) => setNameDraft(event.target.value)} onKeyDown={(event) => event.key === "Enter" && begin()} placeholder="닉네임 입력" aria-label="닉네임" /><button onClick={begin}>여정 시작하기</button></section></div>}
    <main className="game-shell"><section className="topbar"><div className="brand"><span className="brand-spark">✦</span><span>예수 키우기</span></div><div className="battle-stat">⚔ 전투력 <b>{fmt(jesusAttack)}</b></div><div className="love-total"><span>♥</span> 애정도 <strong>{fmt(love)}</strong></div><button className="profile-button" onClick={() => setProfileOpen(true)} aria-label="프로필 열기">☺</button></section>
      <section className="game-grid"><aside className="evolution panel"><div className="panel-heading"><p>EVOLUTION</p><h2>성장 여정</h2></div><ol className="stage-list">{stages.map((item, index) => <li key={item.title} className={index === stageIndex ? "active" : index < stageIndex ? "done" : ""}><span className="step-dot">{stageDots[index] ? "♥" : index + 1}</span><div><b>{index + 1}단계 · {item.title}</b><small>{fmt(item.love * 2)} 애정도</small></div></li>)}</ol></aside>
        <section className="play-area"><div className={`stage-card stage-${stageIndex} ${evolutionBurst ? "is-evolving" : ""}`}><p className="eyebrow">현재 모습 · {stageIndex + 1} / 10</p><h1>{stage.title}</h1><p className="stage-mood">{stage.mood}</p>{evolutionBurst && <div className="evolution-alert"><span>✦</span><b>진화 성공!</b><small>{stage.title} 해금</small></div>}<button className={`character-button aura-${stage.aura}`} onClick={clickJesus} aria-label={`예수님을 눌러 애정도 ${clickPower} 얻기`}><span className="rays" /><span className="halo" /><span className="evolution-sprite" style={{ backgroundPosition: `${stageIndex % 2 ? "100%" : "0%"} ${Math.floor(stageIndex / 2) * 25}%` }} /><span className="stage-ribbon">{stageIndex >= 7 ? "✦ 평화의 빛 ✦" : stageIndex >= 4 ? "따뜻한 사랑" : "작은 시작"}</span>{popups.map((popup) => <span className="love-popup" key={popup.id} style={{ left: popup.x, top: popup.y }}>+{popup.amount} ♥</span>)}</button><div className="click-callout"><span>예수를 눌러주세요</span><b>+{clickPower} ♥</b></div></div><div className="next-progress">{nextStage ? <><span>다음 진화: <b>{nextStage.title}</b></span><span>{fmt(Math.max(0, nextStage.love - love))} ♥ 남음</span></> : <><span>최종 진화 완료!</span><span>사랑이 가득해요</span></>}<div className="progress-track"><i style={{ width: `${Math.max(4, progress)}%` }} /></div></div></section></section>
      <div className="bottom-dock"><div className="dock-stat"><span>☀</span><div><small>천사단 자동 공격</small><b>초당 {fmt(angelAttack)} 피해</b></div></div><button className="adventure-button" onClick={() => setDungeonOpen(true)}>⚔ 모험 <i>→</i></button><button className="open-shop" onClick={() => setShopOpen(true)}><span>🎁</span> 선물 상점</button></div>
      {shopOpen && <div className="shop-overlay" role="dialog" aria-modal="true" aria-label="상점" onMouseDown={() => setShopOpen(false)}><section className="shop-modal" onMouseDown={(event) => event.stopPropagation()}><div className="shop-modal-head"><div><p>BLESSING & ANGEL SHOP</p><h2>마음의 선물</h2><span>애정도와 은총으로 여정을 더 빠르게 완성하세요.</span></div><button onClick={() => setShopOpen(false)} aria-label="상점 닫기">×</button></div><div className="shop-list">{upgrades.map((item) => { const cost = price(item); return <button className="shop-item" key={item.id} onClick={() => buy(item)} disabled={love < cost}><span className="item-icon">{item.icon}</span><span className="item-copy"><b>{item.name} <em>Lv.{levels[item.id] ?? 0}</em></b><small>{item.description}</small></span><span className="cost">♥ {fmt(cost)}</span></button>; })}</div><div className="angel-shop-head"><span>✧ 천사 고용소</span><b>은총 {fmt(grace)}</b></div><div className="shop-list angel-list">{angels.map((angel) => { const cost = angelPrice(angel); return <button className="shop-item angel-item" key={angel.id} onClick={() => hire(angel)} disabled={grace < cost}><span className="item-icon">{angel.icon}</span><span className="item-copy"><b>{angel.name} <em>Lv.{angelLevels[angel.id] ?? 0}</em></b><small>{angel.title} · 자동 공격 +{angel.damage}</small></span><span className="cost">✧ {fmt(cost)}</span></button>; })}</div></section></div>}
      {dungeonOpen && <div className="shop-overlay adventure-overlay" role="dialog" aria-modal="true" aria-label="모험" onMouseDown={() => setDungeonOpen(false)}><section className="shop-modal adventure-modal" onMouseDown={(event) => event.stopPropagation()}><div className="shop-modal-head"><div><p>72 DEMON CHRONICLE</p><h2>악마 보스 모험</h2><span>던전을 순서대로 돌파하고 은총을 얻으세요.</span></div><button onClick={() => setDungeonOpen(false)} aria-label="모험 닫기">×</button></div><div className="dungeon-list">{dungeons.map((dungeon, index) => { const open = (index === 0 || cleared.includes(index - 1)) && stageIndex >= dungeon.stage; const done = cleared.includes(index); return <button key={dungeon.name} className={`dungeon-card ${open ? "" : "locked"} ${done ? "cleared" : ""}`} style={{ "--boss": dungeon.color } as React.CSSProperties} disabled={!open} onClick={() => enterDungeon(index)}><span className="boss-emblem">{open ? dungeon.icon : "🔒"}</span><span><small>{index + 1}번째 봉인 {done && "· 정화 완료"}</small><b>{dungeon.name}</b><em>{dungeon.epithet}</em></span><strong>{open ? `보상 ✧ ${fmt(dungeon.reward)}` : `${dungeon.stage + 1}단계 필요`}</strong></button>; })}</div></section></div>}
      {activeBoss && <div className="battle-overlay"><section className={`battle-arena ${battleState}`}><button className="battle-close" onClick={() => setActiveDungeon(null)} aria-label="전투 나가기">×</button><p className="battle-kicker">72 악마 보스전 · {activeDungeon! + 1}번째 봉인</p><div className="boss-stage" style={{ "--boss": activeBoss.color } as React.CSSProperties}><div className="boss-glow" /><span className="boss-icon">{activeBoss.icon}</span><h2>{activeBoss.name}</h2><p>{activeBoss.epithet}</p>{effects.map((effect) => <span key={effect.id} className={`battle-effect ${effect.kind}`}>{effect.text}</span>)}</div><div className="hp-block"><div><span>BOSS HP</span><b>{fmt(Math.max(enemyHp, 0))} / {fmt(activeBoss.hp)}</b></div><i><em style={{ width: `${Math.max(0, enemyHp / activeBoss.hp * 100)}%` }} /></i></div>{battleState === "victory" ? <div className="victory-panel"><span>✦</span><b>{activeBoss.name} 정화 성공!</b><small>은총 {fmt(activeBoss.reward)}을 얻었습니다.</small><button onClick={() => setActiveDungeon(null)}>모험으로 돌아가기</button></div> : <><div className="angel-squad"><span>자동 전투 · 천사단</span><b>초당 {fmt(angelAttack)} 피해</b><div>{angels.map((angel) => (angelLevels[angel.id] ?? 0) > 0 && <i key={angel.id}>{angel.icon}<small>Lv.{angelLevels[angel.id]}</small></i>)}</div></div><div className="skill-row"><button className="skill strike" disabled={!cooldowns.strike} onClick={() => useSkill("strike")}><span>✦</span><b>빛의 일격</b><small>{fmt(jesusAttack * 3)} 피해 · 2초</small></button><button className="skill burst" disabled={!cooldowns.burst} onClick={() => useSkill("burst")}><span>☀</span><b>은총 폭발</b><small>{fmt(jesusAttack * 8)} 피해 · 7초</small></button><button className="skill judgment" disabled={!cooldowns.judgment} onClick={() => useSkill("judgment")}><span>⚜</span><b>성광 심판</b><small>{fmt(jesusAttack * 16)} 피해 · 12초</small></button></div></>}</section></div>}
      {profileOpen && <div className="intro-overlay profile-overlay" onMouseDown={() => setProfileOpen(false)}><section className="intro-card profile-card" onMouseDown={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setProfileOpen(false)}>×</button><div className="profile-heading"><span>☺</span><div><h2>{nickname}</h2><small>{startedAt ? `${date(startedAt)} 시작` : "새로운 여정"}</small></div></div><button className="record-button" onClick={() => { setProfileOpen(false); setRecordOpen(true); }}>📜 성장 기록 <b>›</b></button></section></div>}
      {recordOpen && <div className="intro-overlay profile-overlay" onMouseDown={() => setRecordOpen(false)}><section className="intro-card record-card" onMouseDown={(event) => event.stopPropagation()}><div className="record-title"><h2>성장 기록</h2><button className="modal-close" onClick={() => setRecordOpen(false)}>×</button></div><ol>{startedAt && <li><i>♥</i><div><b>여정 시작</b><small>{date(startedAt)}</small></div></li>}{stages.map((item, index) => milestones[index] && <li key={item.title}><i>{index + 1}</i><div><b>{item.title} 첫 도달</b><small>{date(milestones[index])}</small></div></li>)}</ol></section></div>}
    </main>
  </>;
}
